### ISSUE TITLE
下载v1.9.21.1 oracle_mig_mysql_linux_x86.zip后执行异常

### ISSUE THREAD

**Issue by lixian1997** [iverycd/oracle_to_mysql#1]
pjgglapp001:~/mig/oracle_to_mysql # ./oracle_mig_mysql -c
Traceback (most recent call last):
  File "dbutils/pooled_db.py", line 320, in connection
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "oracle_mig_mysql.py", line 653, in <module>
  File "oracle_mig_mysql.py", line 606, in main
  File "db_info.py", line 412, in get_info
  File "configDB.py", line 62, in __init__
  File "configDB.py", line 93, in __get_pool
  File "dbutils/pooled_db.py", line 263, in __init__
  File "dbutils/pooled_db.py", line 263, in <listcomp>
  File "dbutils/pooled_db.py", line 333, in dedicated_connection
  File "dbutils/pooled_db.py", line 322, in connection
  File "dbutils/pooled_db.py", line 271, in steady_connection
  File "dbutils/steady_db.py", line 137, in connect
  File "dbutils/steady_db.py", line 190, in __init__
  File "dbutils/steady_db.py", line 208, in _create
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "/root/mig/oracle_to_mysql/oracle_client/lib/libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
[98153] Failed to execute script oracle_mig_mysql

**Comment by iverycd** [comment]
Linux环境需要在执行前设定oracle环境变量，可以看下首页文档章节`开箱即用的二进制可执行文件`
### :trident:全库迁移

#### Linux环境

1、进入迁移工具目录

```bash
[root@localhost opt]# cd /opt/oracle_to_mysql
```


2、运行环境变量脚本

```bash
[root@localhost ]# sh env_ora.sh 

```

![image](https://user-images.githubusercontent.com/35289289/191475634-d6788075-bfd6-45af-87e3-0d779b5ddd51.png)


:warning:注意：此步骤仅Linux环境需要，Windows以及MacOS无需执行

**Comment by lixian1997** [comment]
Traceback (most recent call last):
  File "oracle_mig_mysql.py", line 634, in <module>
  File "oracle_mig_mysql.py", line 587, in main
  File "db_info.py", line 494, in get_info
  File "oracle_mig_mysql.py", line 71, in write
UnicodeEncodeError: 'latin-1' codec can't encode character '\uff1a' in position 31: ordinal not in range(256)
[40415] Failed to execute script oracle_mig_mysql

**Comment by iverycd** [comment]
你的数据库版本麻烦发下

**Comment by lixian1997** [comment]
mysql 8

**Comment by iverycd** [comment]
方便的话麻烦发个oracle表结构的备份给我，我测下，ora_kay@163.com

**Comment by iverycd** [comment]
或者提供下操作系统版本以及终端语言，数据库源库跟目标库版本号，字符集，我找个环境测下

**Comment by lixian1997** [comment]
linux version 4.12.14-122.116-default（gcc version 4.8.5 ( SUSE Linux ) )
en_US
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0-Production
mysql 8.0.23

**Comment by iverycd** [comment]
ok

**Comment by iverycd** [comment]
麻烦补充下字符集oracle是zhs16gbk还是utf8，还有MySQL是utf8mb3，还是utf8mb4

**Comment by lixian1997** [comment]
utf8mb4
utf8

**Comment by iverycd** [comment]
1、试了下在非root用户，比如`oracle`用户执行此工具会由于操作系统环境变量`LANG`变量引发异常
2、解决方法是启动工具前执行`export LANG=en_US.UTF-8`

![image](https://user-images.githubusercontent.com/35289289/192685051-b9dcf2b0-07f3-42ad-8f23-049d680ebe8f.png)

3、非常感谢你提的issue :thumbsup:

**Comment by lixian1997** [comment]
好像还是不行，是要和oracle客户端字符集一致吗？
select userenv('language') from dual
SIMPLIFIED CHINESE_CHINA_AL32UTF-8

**Comment by iverycd** [comment]
麻烦看下你当前用户的环境变量

**Comment by lixian1997** [comment]
2022-09-28 07:00:43
Traceback (most recent call last):
  File "oracle_mig_mysql.py", line 634, in <module>
  File "oracle_mig_mysql.py", line 587, in main
  File "db_info.py", line 494, in get_info
  File "oracle_mig_mysql.py", line 71, in write
UnicodeEncodeError: 'latin-1' codec can't encode character '\uff1a' in position 31: ordinal not in range(256)
[84073] Failed to execute script oracle_mig_mysql
pshfhjgglapp001:~/mig/oracle_to_mysql # echo $LANG
en_US.UTF-8

**Comment by iverycd** [comment]
已发布新的release，请使用`v1.9.28.1`版本

**Comment by iverycd** [comment]
已发布新的release`v1.9.28.3`，麻烦请用这个试下

**Comment by lixian1997** [comment]
成功了，谢谢，但是我没有外键的时候，会报这个错，虽然没有啥影响

2022-09-28 09:18:28
START CREATE FOREIGN KEY
Traceback (most recent call last):
  File "oracle_mig_mysql.py", line 634, in <module>
  File "oracle_mig_mysql.py", line 599, in main
  File "db_info.py", line 931, in fk
  File "configDB.py", line 140, in fetch_all
  File "configDB.py", line 129, in __execute
  File "dbutils/steady_db.py", line 598, in tough_method
cx_Oracle.DatabaseError: ORA-00904: "WMSYS"."WM_CONCAT": \u6807\u8bc6\u7b26\u65e0\u6548
[69690] Failed to execute script oracle_mig_mysql

**Comment by iverycd** [comment]
可以的话麻烦发下外键相关的表结构定义创建语句，可以把表名，列名做无公害处理，我再测下

**Comment by iverycd** [comment]
> 成功了，谢谢，但是我没有外键的时候，会报这个错，虽然没有啥影响
> 
> 2022-09-28 09:18:28 START CREATE FOREIGN KEY Traceback (most recent call last): File "oracle_mig_mysql.py", line 634, in File "oracle_mig_mysql.py", line 599, in main File "db_info.py", line 931, in fk File "configDB.py", line 140, in fetch_all File "configDB.py", line 129, in __execute File "dbutils/steady_db.py", line 598, in tough_method cx_Oracle.DatabaseError: ORA-00904: "WMSYS"."WM_CONCAT": \u6807\u8bc6\u7b26\u65e0\u6548 [69690] Failed to execute script oracle_mig_mysql

在11g环境可以使用`wm_contact 函数`，但是oracle自12c开始摒弃了`wm_contact 函数`，所以在查询外键定义的时候返回异常，目前已发布新的release `v1.9.28.4`解决了这个问题，我在本地19c环境试了下执行ok，还是:thumbsup:非常感谢你:thumbsup:发现这个bug

**Comment by lixian1997** [comment]
这个依赖怎么装呀，我装的依赖好像有问题

**Comment by iverycd** [comment]
> 

你装的是哪个依赖有问题

**Comment by iverycd** [comment]
> 这个依赖怎么装呀，我装的依赖好像有问题

提供下报错或者截图

**Comment by lixian1997** [comment]
谢谢，好像搞定了

**Comment by iverycd** [comment]
没事，如果后续有问题也可以发邮件给我ora_kay@163.com

**Comment by lixian1997** [comment]
当Oracle表有主键时，工具迁移mysql是先create table后再加主键。
但是Mysql8的有一个特性是只能建有主键的表，所以表结构无法create成功。

请问能优化在建表时加上主键，以及当oracle表中无主键时，新建一个主键自增字段吗？

**Comment by iverycd** [comment]
我下午看下&nbsp;


kay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 中午12:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [iverycd/oracle_to_mysql] 下载v1.9.21.1 oracle_mig_mysql_linux_x86.zip后执行异常 (Issue #1)





 
当Oracle表有主键时，工具迁移mysql是先create table后再加主键。
 但是Mysql8的有一个特性是只能建有主键的表，所以表结构无法create成功。
 
请问能优化在建表时加上主键，以及当oracle表中无主键时，新建一个主键自增字段吗？

**Comment by lixian1997** [comment]
1、oracle表结构非空字段，迁移至mysql后，非空约束丢失。
2、default值如果是配置了to_date, to_char之类的函数的时候，程序报错。

**Comment by iverycd** [comment]
麻烦提供下表结构SQL，我看下&nbsp;


kay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 中午1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [iverycd/oracle_to_mysql] 下载v1.9.21.1 oracle_mig_mysql_linux_x86.zip后执行异常 (Issue #1)





 
1、oracle表结构非空字段，迁移至mysql后，非空约束丢失。
 2、default值如果是配置了to_date, to_char之类的函数的时候，程序报错。

**Comment by lixian1997** [comment]
create table JOB{
CREATEDATE VARCHAR2(8) DEFAULT to_char(sysdate,'yyyyMMdd') not null,
CREATETIME VARCHAR2(6) DEFAULT to_char(sysdate,'hh24miss') not null
}

**Comment by iverycd** [comment]
据我能了解的资料而言，MySQL暂不支持默认值内包含函数


kay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iverycd/oracle_to_mysql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月20日(星期一) 中午1:09
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [iverycd/oracle_to_mysql] 下载v1.9.21.1 oracle_mig_mysql_linux_x86.zip后执行异常 (Issue #1)





 
1、oracle表结构非空字段，迁移至mysql后，非空约束丢失。
 2、default值如果是配置了to_date, to_char之类的函数的时候，程序报错。

**Comment by iverycd** [comment]
> 当Oracle表有主键时，工具迁移mysql是先create table后再加主键。 但是Mysql8的有一个特性是只能建有主键的表，所以表结构无法create成功。
> 
> 请问能优化在建表时加上主键，以及当oracle表中无主键时，新建一个主键自增字段吗？

`V1.3.21`版本已修复
https://github.com/iverycd/oracle_to_mysql/releases/tag/v1.3.21

**Comment by lixian1997** [comment]
(3750, "Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.")

**Comment by lixian1997** [comment]
非空字段约束没有迁移

create table JOB{
CREATEDATE VARCHAR2(8)  not null,
CREATETIME VARCHAR2(6)  not null
}

**Comment by iverycd** [comment]
> 非空字段约束没有迁移
> 
> create table JOB{ CREATEDATE VARCHAR2(8) not null, CREATETIME VARCHAR2(6) not null }

v1.3.24已修复

**Comment by lixian1997** [comment]
(3750, "Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.")

mysql全局设置了sql_require_primary_key，所以就改不掉了

**Comment by lixian1997** [comment]
可不可以加一个参数，允许在建表的时候先建立主键，并且这个开关开启时，会检查oracle表是否有主键，如果没有则要求用户建立完主键后再迁移。

**Comment by iverycd** [comment]
麻烦提供你使用的MySQL版本，我本地是全局sql_require_primary_key=on，代码里是设置的会话级别“set session sql_require_primary_key=off”，我在我环境8.0.26测试正常，你不妨单独在navicate测下set session sql_require_primary_key=off执行之后再创建没有主键的表
&nbsp;


kay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 下午3:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [iverycd/oracle_to_mysql] 下载v1.9.21.1 oracle_mig_mysql_linux_x86.zip后执行异常 (Issue #1)





 
(3750, "Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.")
 
mysql全局设置了sql_require_primary_key，所以就改不掉了

**Comment by lixian1997** [comment]
8.0.25

然后使用v1.3.24版本，报以下错：
 GENERATE REPORT ON CURRENT DIRECTORY "run_report.html"
Traceback (most recent call last):
  File "oracle_to_mysql/oracle_mig_mysql.py", line 666, in <module>
  File "oracle_to_mysql/oracle_mig_mysql.py", line 654, in main
  File "db_info.py", line 676, in run_info
  File "dbutils/steady_db.py", line 687, in tough_method
  File "dbutils/steady_db.py", line 606, in tough_method
  File "pymysql/cursors.py", line 148, in execute
  File "pymysql/cursors.py", line 310, in _query
  File "pymysql/connections.py", line 548, in query
  File "pymysql/connections.py", line 775, in _read_query_result
  File "pymysql/connections.py", line 1156, in read
  File "pymysql/connections.py", line 725, in _read_packet
  File "pymysql/protocol.py", line 221, in raise_for_error
  File "pymysql/err.py", line 143, in raise_mysql_exception
pymysql.err.OperationalError: (1055, "Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'my_mig_task_info.detail' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[15499] Failed to execute script 'oracle_mig_mysql' due to unhandled exception!

**Comment by iverycd** [comment]
麻烦你在MySQL库里执行这个命令看下数据库参数信息
show variables like '%sql_mode%';

**Comment by lixian1997** [comment]
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

**Comment by iverycd** [comment]
> ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

这是由于你的MySQL参数里只允许包含聚合函数之后才能使用group by，也就是严格模式，上面数据库客户端执行set session sql_require_primary_key=off执行之后再创建没有主键的表，这个试了吗

**Comment by iverycd** [comment]
> 8.0.25
> 
> 然后使用v1.3.24版本，报以下错： GENERATE REPORT ON CURRENT DIRECTORY "run_report.html" Traceback (most recent call last): File "oracle_to_mysql/oracle_mig_mysql.py", line 666, in File "oracle_to_mysql/oracle_mig_mysql.py", line 654, in main File "db_info.py", line 676, in run_info File "dbutils/steady_db.py", line 687, in tough_method File "dbutils/steady_db.py", line 606, in tough_method File "pymysql/cursors.py", line 148, in execute File "pymysql/cursors.py", line 310, in _query File "pymysql/connections.py", line 548, in query File "pymysql/connections.py", line 775, in _read_query_result File "pymysql/connections.py", line 1156, in read File "pymysql/connections.py", line 725, in _read_packet File "pymysql/protocol.py", line 221, in raise_for_error File "pymysql/err.py", line 143, in raise_mysql_exception pymysql.err.OperationalError: (1055, "Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'my_mig_task_info.detail' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") [15499] Failed to execute script 'oracle_mig_mysql' due to unhandled exception!

这是由于你的MySQL参数里只允许包含聚合函数之后才能使用group by，也就是严格模式,这个报错是最后生成迁移报告，影响不大

**Comment by lixian1997** [comment]
1、写个shell，接受用户以参数输入，在shell中用临时文件的方式生成配置文件、自定义表。
2、迁移后检查，提示出哪些表缺少主键

**Comment by lixian1997** [comment]
为什么版本号从1.9-1.10，然后又变成了1.3啊，1.3是单线程吗，迁移速率有点慢啊。oracle 12G的数据，1063W条，5小时迁移了930W，linux内存是8G的，有5.2G在跑mysqld

**Comment by lixian1997** [comment]
> ./oracle_mig_mysql -d
2023-03-29 04:04:46.270637 run begin tool defaultencoding-> utf-8  sys.stdin.encoding-> UTF-8 sys.stdout.encoding-> UTF-8
connect database failed please check oracle client is correct or network is ok
 Error while trying to retrieve text for error ORA-01804
Error while trying to retrieve text for error ORA-01804
+-----------------------------------------+
| Oracle Migrate MySQL Tool               |
+-----------------------------------------+
| MySQL 5.7 and Oracle 11g higher Support |
| Powered By IVERYCD                      |
| Version v1.3.24                         |
+-----------------------------------------+

Source Database information:
Traceback (most recent call last):
  File "oracle_to_mysql/oracle_mig_mysql.py", line 666, in <module>
  File "oracle_to_mysql/oracle_mig_mysql.py", line 617, in main
  File "db_info.py", line 463, in get_info
AttributeError: 'DbMetadata' object has no attribute 'oracle_info'
[18642] Failed to execute script 'oracle_mig_mysql' due to unhandled exception!

**Comment by lixian1997** [comment]
./oracle_mig_mysql -c -d -m 时 可否无需在命令行界面键入“y”进行迁移前确认？

**Comment by iverycd** [comment]
你好，这一点我有考虑过，导出成平面文件再导入到MySQL，需要在操作系统生成文件，此动作会额外带来磁盘io读写，MySQL没有像pgsql的copy方法支持远程数据写入，目前来看在线迁移方式只有多进程读写并行insert方式最有效率，当然也得看源、目的库服务器性能


kay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iverycd/oracle_to_mysql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月17日(星期一) 下午5:01
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [iverycd/oracle_to_mysql] 下载v1.9.21.1 oracle_mig_mysql_linux_x86.zip后执行异常 (Issue #1)





 
落地生成分隔符文件，再用load data去导入，速度会不会快一点？

**Comment by lixian1997** [comment]
-d 仅迁移数据时，是不是单线程的，现在能支持多线程吗

**Comment by lixian1997** [comment]
-m 仅迁移自定义表结构时，并没有迁移自定义表，而是迁移了所有表

**Comment by lixian1997** [comment]
oracle 8G内存、mysql32G内存，工具跑在mysql机器上，迁移112列、1000W条、12.5G的一张表，需要6小时，这个速度慢是因为字段数过多的原因吗，是否有优化空间？

**Comment by lixian1997** [comment]
oracle 8G内存、mysql32G内存，工具跑在mysql机器上，迁移112列、1000W条、12.5G的一张表，需要6小时，这个速度慢是因为字段数过多的原因吗，是否有优化空间？

**Comment by lixian1997** [comment]
迁移大数据会在mysql bin_log文件夹下产生大量日志，占用磁盘空间，这是否也是速度慢的原因，是否可以关闭？

**Comment by lixian1997** [comment]
linux 11SP4 中 /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by ./oracle_mig_mysql)

**Comment by iverycd** [comment]
在大量增删改操作的时候会生成很多binlog日志，会对磁盘io产生负载压力，在进行大数据量导入的时候建议关闭binlog，方法参考网上：
https://www.cnblogs.com/king-dom/articles/15791013.html
&nbsp;


kay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 上午8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [iverycd/oracle_to_mysql] 下载v1.9.21.1 oracle_mig_mysql_linux_x86.zip后执行异常 (Issue #1)





 
迁移大数据会在mysql bin_log文件夹下产生大量日志，占用磁盘空间，这是否也是速度慢的原因，是否可以关闭？

**Comment by iverycd** [comment]
跟源库磁盘性能，内存大小，网络带宽，目标库磁盘写性能都有关系，可在迁移前使用磁盘性能测试工具sysbench或者其他工具测下磁盘IOPS是多少
&nbsp;


kay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 上午8:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [iverycd/oracle_to_mysql] 下载v1.9.21.1 oracle_mig_mysql_linux_x86.zip后执行异常 (Issue #1)





 
oracle 8G内存、mysql32G内存，工具跑在mysql机器上，迁移112列、1000W条、12.5G的一张表，需要6小时，这个速度慢是因为字段数过多的原因吗，是否有优化空间？

**Comment by iverycd** [comment]
> oracle 8G内存、mysql32G内存，工具跑在mysql机器上，迁移112列、1000W条、12.5G的一张表，需要6小时，这个速度慢是因为字段数过多的原因吗，是否有优化空间？

跟源库磁盘性能，内存大小，网络带宽，目标库磁盘写性能都有关系，可在迁移前使用磁盘性能测试工具sysbench或者其他工具测下磁盘IOPS是多少

以下是我使用的环境磁盘iops

![image](https://user-images.githubusercontent.com/35289289/236412087-8b3e308c-9d2c-4afc-ae1f-4065b1e8f818.png)

**Comment by lixian1997** [comment]
1、根据Mysql基线，我修改了源码（最后生成报告时不报错的异常）：MySQL参数里只允许包含聚合函数之后才能使用group by，也就是严格模式。
2、使用是否需要收费？

**Comment by iverycd** [comment]
> 1、根据Mysql基线，我修改了源码（最后生成报告时不报错的异常）：MySQL参数里只允许包含聚合函数之后才能使用group by，也就是严格模式。
> 2、使用是否需要收费？

1、报告你也可以根据需要是否展示（非必须项），为了写的方便使用的非严格模式下的聚合函数查询，当然有条件也可以自行更改SQL语句
2、免费

**Comment by iverycd** [comment]
> 我可以自由修改和使用吗？

可以

**Comment by iverycd** [comment]
> 我可以自由修改和使用吗？

可以

**Comment by iverycd** [comment]
> 为什么版本号从1.9-1.10，然后又变成了1.3啊，1.3是单线程吗，迁移速率有点慢啊。oracle 12G的数据，1063W条，5小时迁移了930W，linux内存是8G的，有5.2G在跑mysqld

现在用golang重新写了个工具，你试下新项目https://github.com/iverycd/OracleSync2MySQL
