### ISSUE TITLE
最新版为啥windows没有包想自己运行发现没有以来配置文件

### ISSUE THREAD

**Issue by whp98** [iverycd/oracle_to_mysql#12]

**Comment by iverycd** [comment]
> No description provided.

已发布

**Comment by whp98** [comment]
我已经用脚本跑起来了 你可以把这俩脚本加进去一个是虚拟环境创建，一个是把依赖提取到一个txt文件种
[环境和依赖冻结.zip](https://github.com/iverycd/oracle_to_mysql/files/12158549/default.zip)

**Comment by whp98** [comment]
你这回复挺快

**Comment by iverycd** [comment]
> 我已经用脚本跑起来了 你可以把这俩脚本加进去一个是虚拟环境创建，一个是把依赖提取到一个txt文件种
> [环境和依赖冻结.zip](https://github.com/iverycd/oracle_to_mysql/files/12158549/default.zip)

好的，我试下
