### ISSUE TITLE
能够提供下，依赖的各个python包的版本吗

### ISSUE THREAD

**Issue by cnscottluo** [iverycd/oracle_to_mysql#13]

**Comment by iverycd** [comment]
> No description provided.
Python 3.8.2
cx_Oracle==8.3.0
cx_Oracle==8.3.0
DBUtils==3.0.2
html_table==1.0
prettytable==3.8.0
PyMySQL==1.0.2

**Comment by cnscottluo** [comment]
> > No description provided.
> > Python 3.8.2
> > cx_Oracle==8.3.0
> > cx_Oracle==8.3.0
> > DBUtils==3.0.2
> > html_table==1.0
> > prettytable==3.8.0
> > PyMySQL==1.0.2

谢谢
