### ISSUE TITLE
-m 模式下为什么显示 Migration Mode:full database

### ISSUE THREAD

**Issue by wxa56** [iverycd/oracle_to_mysql#4]

**Comment by iverycd** [comment]
-m是仅创建表结构，会在下个版本中修复这个“显示模式问题”

**Comment by iverycd** [comment]
v1.3.21已修复
https://github.com/iverycd/oracle_to_mysql/releases/tag/v1.3.21

**Comment by iverycd** [comment]
v1.3.21版本已修复




kay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iverycd/oracle_to_mysql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 中午11:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[iverycd/oracle_to_mysql] -m 模式下为什么显示 Migration Mode:full database (Issue #4)
