### ISSUE TITLE
求助打包的问题

### ISSUE THREAD

**Issue by shining-snail** [iverycd/oracle_to_mysql#6]
我们拉取了源代码，考虑自己打包一个可执行版本使用，在使用pack.sh打包以后，在新的linux环境运行会提示有些库不存在，求助这个问题该怎么解决？

我之前尝试了在centos7上打包，然后放到suse linux运行，会提示readline版本不存在。我又尝试在高版本的suse linux上打包，放到同样版本suse linux运行没有问题，但是放到低版本的suse linux运行会提示 glibc版本无法找到。

感觉这个打包程序没有完全静态打包，似乎还是比较挑平台的，但是用你的发布版本执行就没有这类问题，想了解下使用pack.sh打包和你的发布版本的差异主要在哪里呢？

**Comment by iverycd** [comment]
我的IDE环境主要是在centos下使用Anaconda的python进行开发，以下是我使用的版本，你可参考下

OS:CentOS Linux release 7.5.1804 (Core) 并在此安装了Anaconda环境
Anaconda安装包名称:Anaconda3-2019.07-Linux-x86_64.sh
Anaconda 环境python version:Python 3.7.3

附anaconda下载地址
anaconda的历史版本
https://repo.anaconda.com/archive/

**Comment by shining-snail** [comment]
> 我的IDE环境主要是在centos下使用Anaconda的python进行开发，以下是我使用的版本，你可参考下
> 
> OS:CentOS Linux release 7.5.1804 (Core) 并在此安装了Anaconda环境 Anaconda安装包名称:Anaconda3-2019.07-Linux-x86_64.sh Anaconda 环境python version:Python 3.7.3
> 
> 附anaconda下载地址 anaconda的历史版本 https://repo.anaconda.com/archive/

谢谢，我已经找到原因。pyinstaller打包的程序底层不能有太大差异，比如平台的glibc版本接近，那么无论是centos，ubuntu还是suse打包都可以在这些系统上直接执行，但是若glibc版本相差过大就需要在对应版本glibc上打包，这个工具不是跨平台的，这就说得通了，再次感谢！
