### ISSUE TITLE
迁移只读view

### ISSUE THREAD

**Issue by shining-snail** [iverycd/oracle_to_mysql#7]
大神你好，我在测试一个oracle迁移mysql的样例，我是用了oracle的示例方案hr，里面有1个view是read only的，但是mysql估计是不支持创建read only的视图，因此在迁移报告中出现如下的报错：
    create view EMP_DETAILS_VIEW AS
SELECT
    e.employee_id,
    e.job_id,
    e.manager_id,
    e.department_id,
    d.location_id,
    l.country_id,
    e.first_name,
    e.last_name,
    e.salary,
    e.commission_pct,
    d.department_name,
    j.job_title,
    l.city,
    l.state_province,
    c.country_name,
    r.region_name
FROM
    employees e,
    departments d,
    jobs j,
    locations l,
    countries c,
    regions r
WHERE
    e.department_id = d.department_id   AND d.location_id = l.location_id   AND l.country_id = c.country_id   AND c.region_id = r.region_id   AND j.job_id = e.job_id
WITH
    READ ONLY

/* (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ ONLY' at line 29") */

CREATE VIEW ERROR!

我只需要去除最后的read only选项就能创建成功，我估计自己测试环境内不太会有这样的情况，所以实操估计碰不上这个问题，是否需要优化按您自己的需求吧，谢谢！

**Comment by iverycd** [comment]
这个正则匹配或者replace替换都行，不改代码的话，就是手动去除
