### ISSUE TITLE
关于link执行的疑问

### ISSUE THREAD

**Issue by shining-snail** [iverycd/oracle_to_mysql#9]
大神你好，我打算在一台机器上执行多个迁移任务，这个时候需要复用程序，但是我不希望复制整个程序，只希望利用同一份可执行程序，日志报告、配置文件可以单独，类似如下的效果：
test@kubemas001:/tmp/test> ls -l
total 36
-rw-r--r-- 1 test dba   260 Jun 18 23:20 config.ini
lrwxrwxrwx 1  test dba    41 Jun 18 23:22 env_ora.sh -> /home/test/oracle_to_mysql/env_ora.sh
drwxr-xr-x 3 test dba  4096 Jun 18 23:23 mig_log
lrwxrwxrwx 1 test dba    45 Jun 18 23:21 oracle_client -> /home/test/oracle_to_mysql/oracle_client/
lrwxrwxrwx 1 test dba    51 Jun 18 23:22 oracle_compare_mysql -> /home/test/oracle_to_mysql/oracle_compare_mysql
lrwxrwxrwx 1 test dba    47 Jun 18 23:21 oracle_mig_mysql -> /home/test/oracle_to_mysql/oracle_mig_mysql
-rw-r--r-- 1 test dba   120 Jun 18 23:22 run_env
-rw-r--r-- 1 test dba 24381 Jun 18 23:23 run_report.html

我使用了ln指令链接可执行程序、oracle客户端、环境配置脚本，而config.ini,run_env等我将在这个目录中独立生成，这样我可以很快复用出第二套迁移环境。当我运行后也验证可以执行，mig_log目录自动建立，看着没问题，但是工具最后提示的路径好像和/tmp/test目录不匹配，提示路径貌似是拿了程序原始文件的路径，但是那个目录下没有生成log（因为在/tmp/test下生成了）

报告如下:

PLEASE CHECK FAILED TABLE DDL IN LOG DIR
Oracle PROCEDURE SAVED TO /home/test/oracle_to_mysql/mig_log/2023_06_18_23_23_09/ddl_function_procedure.sql

MIGATE LOG HAVE SAVED TO /home/test/oracle_to_mysql/mig_log/2023_06_18_23_23_09/
PLEASE SELECT * FROM my_mig_task_info IN TARGET DATABASE
INSERT FAILED TABLE PLEASE CHECK ddl_failed_table.log AND insert_failed_table.log

我看了源码，发现大神在2个py文件使用了不同的逻辑获取exepath，想请教下为什么是这样设计呢？
db_info.py中：
elif platform.system().upper() == 'LINUX' or platform.system().upper() == 'DARWIN':
    exepath = os.path.dirname(os.path.abspath(__file__)) + '/'

oracle_mig_mysql.py中：
lif platform.system().upper() == 'LINUX' or platform.system().upper() == 'DARWIN':
        # exepath = os.path.dirname(os.path.abspath(__file__)) + '/'
        exepath = os.path.dirname(os.path.realpath(sys.argv[0])) + '/'

当使用abspath方法时，我们得到了当前工作目录，当使用realpath方法时，我们得到link对应文件所在的目录。在oracle_mig_mysql.py中，exepath作为参数传递给db_info.py的run_info方法，最后显示的目录路径就是
/home/test/oracle_to_mysql/mig_log/2023_06_18_23_23_09

但是实际上日志写入的路径是link所在的目录：
/tmp/test/mig_log/2023_06_18_23_23_09

看上去是使用了cte_tab的方法在log_path写入日志，这样的话就会写入相对路径中，好像取绝对路径的exepath并没有得到正确路径?

**Comment by iverycd** [comment]
![image](https://github.com/iverycd/oracle_to_mysql/assets/35289289/60bd5bd9-34c6-4a62-ad89-acd6a3a88edf)

这个是我在Mac下获取路径信息有点问题，你可以按照自己的环境去掉DARWIN
